name: "ECHONETLite2MQTT"
description: "ECHONET Lite to MQTT bridge."
version: "v0.0.0"
slug: "echonetlite2mqtt"
arch:
  - aarch64
  - amd64
init: false
host_network: true
services:
  - mqtt:need
ingress: true
ingress_port: 0
map:
  - path: "/addon_config"
    type: addon_config
    read_only: true
  - path: "/ssl"
    type: ssl
    read_only: true
  - path: "/data"
    type: data
    read_only: true
schema:
  MQTT_BROKER: str?
  MQTT_PORT: port?
  MQTT_CLIENT_ID: str?
  MQTT_USERNAME: str?
  MQTT_PASSWORD: password?
  MQTT_OPTION_FILE: str?
  MQTT_CA_FILE: str?
  MQTT_CERT_FILE: str?
  MQTT_KEY_FILE: str?
  MQTT_BASE_TOPIC: str?
  ECHONET_TARGET_NETWORK: str?
  ECHONET_DEVICE_IP_LIST: str?
  ECHONET_COMMAND_TIMEOUT: int?
  ECHONET_DISABLE_AUTO_DEVICE_DISCOVERY: bool?
  ECHONET_ALIAS_FILE: str?
  ECHONET_LEGACY_MULTI_NIC_MODE: bool?
  ECHONET_UNKNOWN_AS_ERROR: bool?


