name: Build and Publish HA Addon

on: [ workflow_dispatch ]
#on: [push, pull_request]

jobs:
  build:
    name: Publish
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy files and modify version
        id: version
        run: |
          rsync -a . ./ha_addon/src/ --exclude './ha_addon/'
          app_version=$(cat ./ha_addon/src/package.json | jq -r '.version')
          sed -i -e "s/_____APP_VERSION_____/${app_version}/" ./ha_addon/config.yaml
          echo "app_version=${app_version}" >> "$GITHUB_OUTPUT" 
      - name: Publish
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --addon \
            --docker-hub ghcr.io/${{ github.actor }} \
            --image echonetlite2mqtt-addon/{arch} \
            --target /data/ha_addon \
      - name: Generate GitHub Apps token
        id: gentoken
        uses: tibdex/github-app-token@v1
        with:
            app_id: ${{ secrets.HA_ADDON_APP_ID }}
            private_key: ${{ secrets.HA_ADDON_PRIVATE_KEY }}
      - name: Checkout HA addon repo
        uses: actions/checkout@v3
        with:
          token: ${{ steps.gentoken.outputs.token }}
          repository: ${{ github.actor }}/home-assistant-addons
          path: addon_repos
      - name: update config.yaml at the HA addon repo
        working-directory: addon_repos
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          cp ../ha_addon/config.yaml echonetlite2mqtt/config.yaml
          git add echonetlite2mqtt/config.yaml
          git commit -m "commit for ${{steps.version.outputs.app_version}}"
          git push origin main